# services:

# # ==========================================
# # Backend (FastAPI)
# # ==========================================
#   backend:
#     build: ./backend
#     container_name: attendance_backend
#     ports:
#       - "8000:8000"
#     env_file:
#       - ./backend/.env
#     depends_on:
#       - redis
#     volumes:
#       - ./backend:/app
#     restart: always
#     networks:
#       - attendance_network


# # ==========================================
# # AI Engine
# # ==========================================
#   ai_engine:
#     build: ./ai_engine
#     container_name: attendance_ai_engine
#     ports:
#       - "9000:9000"
#     env_file:
#       - ./ai_engine/.env
#     volumes:
#       - ./ai_engine:/app
#       - ./ai_engine/insightface_models:/app/insightface_models
#     depends_on:
#       - backend
#     restart: always
#     network_mode: host


# # ==========================================
# # Frontend (Next.js)
# # ==========================================
#   frontend:
#     build:
#       context: ./ai_frontend
#       dockerfile: dockerfile
#     container_name: attendance_frontend
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./ai_frontend:/app
#       - /app/node_modules
#     env_file:
#       - ./ai_frontend/.env.local
#     environment:
#       - WATCHPACK_POLLING=true
#     depends_on:
#       - backend
#     restart: always
#     networks:
#       - attendance_network


# # ==========================================
# # Redis
# # ==========================================
#   redis:
#     image: redis:7
#     container_name: attendance_redis
#     ports:
#       - "6379:6379"
#     volumes:
#       - redis_data:/data
#     restart: always
#     networks:
#       - attendance_network


# # ==========================================
# # WAHA (WhatsApp Automation)
# # ==========================================
#   waha:
#     image: devlikeapro/waha
#     container_name: attendance_waha
#     ports:
#       - "3001:3000"
#     volumes:
#       - ./waha_sessions:/app/.sessions
#     restart: always
#     networks:
#       - attendance_network


# # ==========================================
# # Networks
# # ==========================================
# networks:
#   attendance_network:
#     driver: bridge


# # ==========================================
# # Volumes
# # ==========================================
# volumes:
#   redis_data:


services:

# ==========================================
# Backend (FastAPI)
# ==========================================
  backend:
    build: ./backend
    container_name: attendance_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    volumes:
      - ./backend:/app
    restart: always
    networks:
      - attendance_network


# ==========================================
# AI Engine
# ==========================================
  ai_engine:
    build: ./ai_engine
    container_name: attendance_ai_engine
    # ports:
    #   - "9000:9000"
    env_file:
      - ./ai_engine/.env
    volumes:
      - ./ai_engine:/app
      - ./ai_engine/insightface_models:/app/insightface_models
    depends_on:
      - backend
    restart: always

    # =========================================
    # OFFICE (Kal) — IP Camera LAN pe hai
    # Kal ye uncomment karo aur laptop wala comment karo
    # =========================================
    network_mode: host

    # =========================================
    # LAPTOP (Abhi testing ke liye)
    # Webcam mount kar rahe hain container mein
    # Kal ye comment karo aur office wala uncomment karo
    # =========================================


    
    # devices:
    #   - /dev/video0:/dev/video0
    # privileged: true
    # group_add:
    #   - "44"
    # networks:
    #   - attendance_network


# ==========================================
# Frontend (Next.js)
# ==========================================
  frontend:
    build:
      context: ./ai_frontend
      dockerfile: dockerfile
    container_name: attendance_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./ai_frontend:/app
      - /app/node_modules
    env_file:
      - ./ai_frontend/.env.local
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    restart: always
    networks:
      - attendance_network


# ==========================================
# Redis
# ==========================================
  redis:
    image: redis:7
    container_name: attendance_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - attendance_network


# ==========================================
# WAHA (WhatsApp Automation)
# ==========================================
  waha:
    image: devlikeapro/waha
    container_name: attendance_waha
    ports:
      - "3001:3000"
    volumes:
      - ./waha_sessions:/app/.sessions
    restart: always
    networks:
      - attendance_network
    environment:
      - WAHA_API_KEY=41c3c146b71f4f0793d0b25539696d8d
      - WAHA_DASHBOARD_USERNAME=admin
      - WAHA_DASHBOARD_PASSWORD=5d233c988c4f41a2b947b1c3114a6bee
      - WHATSAPP_SWAGGER_USERNAME=admin
      - WHATSAPP_SWAGGER_PASSWORD=5d233c988c4f41a2b947b1c3114a6bee
      - WAHA_START_SESSION=default  

# ==========================================
# Networks
# ==========================================
networks:
  attendance_network:
    driver: bridge


# ==========================================
# Volumes
# ==========================================
volumes:
  redis_data: