import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "./providers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "AI Based attendance management system",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
    >
      <body 
      className={`${inter.variable}   antialiased`}
      >
        <Providers>

        {children}
        </Providers>
        
        </body>
    </html>
  );
}
